lap_timer:
  ros__parameters:
    odom_topic: /car_state/frenet/odom
    start_window: 0.5
    wrap_threshold: 10.0
    min_lap_time: 3.0
    frame_id: map
    use_position_x_as_s: true
    rviz_text: true
    publish_hud: true
    exact_zero_mode: false
    exact_zero_eps: 0.05
